### ISSUE TITLE
can't load google-maps-api

### ISSUE THREAD

**Issue by JayeshLunkad** [Jam3/google-maps-api#7]
i have just follow the example section 
var mapsapi = require( 'google-maps-api' )( 'api key' );

mapsapi().then( function( maps ) {

  //use the google.maps object as you please
});

then 

npm install google-maps-api
I got following error 

E:\temp\map1\node_modules\google-maps-api\node_modules\scriptjs\dist\script.js:1
2
  var doc = document
            ^

ReferenceError: document is not defined
    at E:\temp\map1\node_modules\google-maps-api\node_modules\scriptjs\dist\scri
pt.js:12:13
    at doc (E:\temp\map1\node_modules\google-maps-api\node_modules\scriptjs\dist
\script.js:8:72)
    at Object.<anonymous> (E:\temp\map1\node_modules\google-maps-api\node_module
s\scriptjs\dist\script.js:11:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\temp\map1\node_modules\google-maps-api\index.js:3:
14)

can you please help ?

**Comment by dascheib** [comment]
Hi.. 

I've got a similar error while trying to use google-maps-api together with grunt.
Is that supposed to work together?

Thank you in advance,
Daniel

**Comment by rocketkittens** [comment]
I have encountered this issue. If you read the error output carefully you will see this package depends on [scriptjs](https://www.npmjs.com/package/scriptjs) which depends on the [document](https://developer.mozilla.org/en-US/docs/Web/API/Document) object.

Since i am looking for a server-side solution, this library does not suit my requirement.

**Comment by AustinHunt** [comment]
Same here! We need to modify this to allow server-side rendering. This is especially frustrating since my library depends on this already.
